import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/app/components/Providers";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers attribute="data-bs-theme" defaultTheme="system">
          {children}
        </Providers>
      </body>
    </html>
  );
}
